### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by Labaman**
Dependencies corrected, new conflicting packages added

### CODE REVIEW

**Review by GregoryLand — COMMENTED** [review]
Reviewing this commit I have some questions.

Checking the dependances for the two packaged binaries

ldd superfgxctl
`
linux-vdso.so.1 (0x00007ffd7ffa9000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7c4b7d0000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f7c4b5c4000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f7c4b8f8000)
`

ldd supergfxd
`
linux-vdso.so.1 (0x00007fff30adf000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fab876f0000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fab874e4000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fab878be000)
`
shows that the package is missing a dependency on gcc-libs but not on dbus.  And when build the package with "depends=('dbus')" i get a warning that it isn't necessary.

In addition I am curious about the justification for adding 'optimus-manager' and 'tlp' to the conflicts array.

**Comment by Labaman** [comment]
Well, I really couldn't find a reference to dbus, except in the package from the G14 repository (asus-linux). Apparently the information is outdated. If you're sure it's unnecessary, then let's exclude it.

Regarding conflicts array: from [official supergfxctl gitlab](https://gitlab.com/asus-linux/supergfxctl):
```
This switcher conflicts with other gpu switchers like optimus-manager, suse-prime
or ubuntu-prime, system76-power, and bbswitch. If you have issues with supergfxd
always defaulting to integrated mode on boot then you will need to check for
stray configs blocking nvidia modules from loading in:

/etc/modprobe.d/
/usr/lib/modprope.d/

ASUS laptops require a kernel 5.15.x or newer. 
```

**Comment by UserSv4** [comment]
> Well, I really couldn't find a reference to dbus, except in the package from the G14 repository (asus-linux). Apparently the information is outdated. If you're sure it's unnecessary, then let's exclude it.
> 
> Regarding conflicts array: from [official supergfxctl gitlab](https://gitlab.com/asus-linux/supergfxctl):
> 
> ```
> This switcher conflicts with other gpu switchers like optimus-manager, suse-prime
> or ubuntu-prime, system76-power, and bbswitch. If you have issues with supergfxd
> always defaulting to integrated mode on boot then you will need to check for
> stray configs blocking nvidia modules from loading in:
> 
> /etc/modprobe.d/
> /usr/lib/modprope.d/
> 
> ASUS laptops require a kernel 5.15.x or newer. 
> ```

How does "tlp" actually conflict with it? I thought "tlp" is not a gpu switcher. I personally do not have any problems running both "tlp" and "supergfxctl" at the same time.

**Comment by GregoryLand** [comment]
Ill start reviewing TLP and see if i can find any conflicts.  It isn't something I have used myself.  It does seem to be able to make changes to GPU frequency limits but I am unsure that there is a conflict yet.

**Comment by GregoryLand** [comment]
After reviewing some of the documentation around tlp it appears that even if there is a conflict tlp.conf offers a way to disable its control over the gpu.  Given that option it think it is better to not set tlp as a conflict.  I will push a patch to remove this conflict shortly.

**Pull request merged**
